name: Build and deploy to gh-pages branch
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-haskell@v1
        with:
          enable-stack: true
      - name: Cache hakyll build
        uses: actions/cache@v3
        with:
          key: "hakyll-stack-work"
          path: |
            hakyll/.stack-work
            ~/.stack
      - uses: freckle/stack-action@v3
        with:
          working-directory: hakyll/
      - name: Rebuild website
        run: stack exec site -- rebuild
        working-directory: hakyll/
      - name: Clone Github pages
        uses: actions/checkout@master
        with:
          ref: gh-pages
          path: site.pub
      - name: Publish site
        run: |
          git config --global user.name "CI Build"
          git config --global user.email "username@users.noreply.github.com"
          make all-pub


        
